//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameProto;
using NetworkCommsDotNet;
using NetworkCommsDotNet.Connections;

public static class LoginExtension
{
    public static void SendLogin(this object obj, Login Login)
    {
        new SendLoginMessage().SendLogin(Login);
    }
}

public class SendLoginMessage
{
    public void SendLogin(Login Login)
    {
        NetworkComms.SendObject("Login", ConnectionConfig.IP, ConnectionConfig.PORT, Login);
    }    
}

public class LoginRegister
{
    public LoginRegister()
    {
        LoginMessageHandler handler = new LoginMessageHandler();
        NetworkComms.AppendGlobalIncomingPacketHandler<Login>("Login", handler.OnHandleMessage);
    }
}
