//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
namespace GameDataTable
{
    public class ActorTable : ConfigTableBase
    {
                public int ActorJobTypeTable_DataID {get;set;}
        public int SexTable_DataID {get;set;}
        public int AbilityTable_DataID {get;set;}

    }

    public class ActorTableManager : TableManager<ActorTable>
    {

    }

    public class ActorTableInstance :TableManagerInstance<ActorTableManager,ActorTableManager>
    {
        public static List<ActorTable> GetActorList()
        {
            return SingleInstance.GetActorList();
        }

        public static ActorTable GetData(int dataID)
        {
            return SingleInstance.GetData(dataID);
        }

        public static bool UpdateData(ActorTable newValue)
        {
            return SingleInstance.UpdateData(newValue);
        }

        public static int Count{ get { return SingleInstance.Count; }}

        public static ActorTable GetLastItme()
        {
            return SingleInstance.GetLastItme();
        }
    }
}
