//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
namespace GameDataTable
{
    public class CreateRoleTable : ConfigTableBase
    {
             public  int ActorTable_DataID  { get; set; } 
       
    }

    public class CreateRoleTableManager : TableManager<CreateRoleTable>
    {

    }

    public class CreateRoleTableInstance :TableManagerInstance<CreateRoleTableManager,CreateRoleTableManager>
    {
        public static List<CreateRoleTable> GetActorList()
        {
            return SingleInstance.GetActorList();
        }

        public static CreateRoleTable GetData(int dataID)
        {
            return SingleInstance.GetData(dataID);
        }

        public static bool UpdateData(CreateRoleTable newValue)
        {
            return SingleInstance.UpdateData(newValue);
        }

        public static int Count{ get { return SingleInstance.Count; }}

        public static CreateRoleTable GetLastItme()
        {
            return SingleInstance.GetLastItme();
        }
    }
}
