//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool once, add the handle feature manually
// </auto-generated>
//------------------------------------------------------------------------------

using GameProto;
using NetworkCommsDotNet;
using NetworkCommsDotNet.Connections;

public class LoginResultMessageHandler
{
	public void OnHandleMessage(PacketHeader header, Connection connection, LoginResult Value)
	{
	}
}
