//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameProto;
using NetworkCommsDotNet;
using NetworkCommsDotNet.Connections;

public static class LoginResultExtension
{
    public static void SendLoginResult(this object obj, LoginResult LoginResult)
    {
        new SendLoginMessage().SendLoginResult(LoginResult);
    }
}

public class SendLoginResultMessage
{
    public void SendLoginResult(LoginResult LoginResult)
    {
        NetworkComms.SendObject("LoginResult", ConnectionConfig.IP, ConnectionConfig.PORT, LoginResult);
    }    
}

public class LoginResultRegister
{
    public LoginResultRegister()
    {
        LoginResultMessageHandler handler = new LoginResultMessageHandler();
        NetworkComms.AppendGlobalIncomingPacketHandler<LoginResult>("LoginResult", handler.OnHandleMessage);
    }
}
